#!/usr/bin/env php
<?php

$autoload = ['vendor/autoload.php', __DIR__ . '/vendor/autoload.php', '../autoload.php'];
$autoload = array_filter($autoload, 'file_exists');
require $autoload[0];

use Symfony\Component\Console\Application;
use SiteAudit\Command;

$application = new Application();
$application->add(new Command\SiteAudit());
$application->add(new Command\AcsfAudit());
$application->add(new Command\MultisiteAudit());
$application->add(new Command\ChecksCommand());
$application->add(new Command\ProfileCreateCommand());
$application->run();
