#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use SiteAudit\Command;

$application = new Application();
$application->add(new Command\SiteAudit());
$application->add(new Command\AcsfAudit());
$application->add(new Command\MultisiteAudit());
$application->add(new Command\ChecksCommand());
$application->add(new Command\ProfileCreateCommand());
$application->run();
