#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use SiteAudit\Command\GreetCommand;
use SiteAudit\Command\SiteAudit;

$application = new Application();
$application->add(new GreetCommand());
$application->add(new SiteAudit());
$application->run();
